CodeKingdom/Models/Entities/Chat.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CodeKingdom.Models.Entities
{
    public class Chat
    {
        public int ID { get; set; }

        [Required]
        public string Message { get; set; }

        [DataType(DataType.Date)]
        public DateTime DateTime { get; set; }

        [Required]
        public string ApplicationUserID { get; set; }
        public int ProjectID { get; set; }

        virtual public ApplicationUser User { get; set; }
        virtual public Project Project { get; set; }
    }
}

CodeKingdom/Models/Entities/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CodeKingdom.Models.Entities
{
    public class Project
    {
        public int ID { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Project name cannot be longer than 50 characters.")]
        public string  Name { get; set; }
        public bool Frozen { get; set; }

        [Required]
        public int FolderID { get; set; }
        
        virtual public Folder Root { get; set; }
        virtual public List<Collaborator> Collaborators { get; set; }
    }
}

CodeKingdom/Controllers/CollaboratorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CodeKingdom.Models;
using Microsoft.AspNet.Identity;
using CodeKingdom.Models.Entities;
using CodeKingdom.Repositories;
using CodeKingdom.Models.ViewModels;
using CodeKingdom.Access;
using CodeKingdom.Business;
using CodeKingdom.Notify;

namespace CodeKingdom.Controllers
{
    [Authorize]
    public class CollaboratorController : Controller
    {
        private CollaboratorStructure collaboratorStructure = new CollaboratorStructure();
        private CollaboratorRepository repository = new CollaboratorRepository();

        /// <summary>
        /// Returns a view for adding a collaborator to a project
        /// </summary>
        /// <param name="id">Project ID</param>
        /// <returns>CollaboratorViewModel</returns>
        public ActionResult Create(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            CollaboratorViewModel viewModel = new CollaboratorViewModel
            {
                ProjectID = id.Value,
                Roles = collaboratorStructure.CreateRoleSelectListForViewModel(),
            };

            if (!isOwner(viewModel))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            return View(viewModel);
        }

        /// <summary>
        /// Adds a new collaborator to a project
        /// </summary>
        /// <param name="collaborator">Collaborator object</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,UserName,RoleID,ProjectID")] CollaboratorViewModel collaborator)
        {
            if (ModelState.IsValid)
            {
                if (!isOwner(collaborator))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }

                if (collaboratorStructure.Create(collaborator))
                {
                    var builder = new UriBuilder(Request.Url.AbsoluteUri)
                    {
                        Path = Url.Action("Index", "Project", new { id = collaborator.ProjectID }),
                        Query = null,
                    };

                    string url = builder.ToString();
                    string message = String.Format("You have been added to a new project, go to {0} to view the project", url);
                    Mailer mail = new Mailer(collaborator.UserName, "Code Kingdom", message);
                    mail.Send();
                    return RedirectToAction("Edit", "Project", new { id = collaborator.ProjectID });
                }
            }

            collaborator.Roles = collaboratorStructure.CreateRoleSelectListForViewModel();

            return View(collaborator);
        }

        /// <summary>
        /// Returns view model to change role for collaborator
        /// </summary>
        /// <param name="id">Collaborator ID</param>
        /// <returns></returns>
        public ActionResult Edit(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Collaborator collaborator = collaboratorStructure.GetCollaboratorById(id.Value);

            if (collaborator == null)
            {
                return HttpNotFound();
            }

            if (!isOwner(collaborator))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            CollaboratorViewModel viewModel = collaboratorStructure.CreateCollaboratorViewModelFromID(collaborator.ID);
            return View(viewModel);
        }

        /// <summary>
        /// Updates collaborator role
        /// </summary>
        /// <param name="collaborator">Collaborator object</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,UserName,RoleID,ProjectID")] CollaboratorViewModel collaborator)
        {
            if (!isOwner(collaborator))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            if (ModelState.IsValid)
            {
                collaboratorStructure.Update(collaborator);
                return RedirectToAction("Edit", "Project", new { id = collaborator.ProjectID });
            }
            return View(collaborator);
        }

        /// <summary>
        /// Ask's for confirmation befor removing collaborator from project
        /// </summary>
        /// <param name="id">Collaborator ID</param>
        /// <returns></returns>
        public ActionResult Delete(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Collaborator collaborator = collaboratorStructure.GetCollaboratorById(id.Value);
            if (!isOwner(collaborator))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            if (collaborator == null)
            {
                return HttpNotFound();
            }

            return View(collaborator);
        }

        /// <summary>
        /// Removes collaborator from project
        /// </summary>
        /// <param name="id">Collaborator id</param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!isOwner(repository.GetById(id)))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            collaboratorStructure.Delete(id);
            return RedirectToAction("Index", "Project");
        }

        /// <summary>
        /// Checks if user is a owner fo the project.
        /// </summary>
        /// <param name="collaborator">Collaborator object</param>
        /// <returns>True if owner, false otherwise</returns>
        protected bool isOwner(Collaborator collaborator)
        {
            string userID = User.Identity.GetUserId();
            ProjectAccess access = new ProjectAccess(collaborator.ProjectID);

            if (!access.IsOwner(userID))
            {
                return false;
            }

            return true;
        }

        /// <summary>
        /// Checks if user is a owner for the project by collaborator view model
        /// </summary>
        /// <param name="collaborator">Collaborator object</param>
        /// <returns>True if owner, false otherwise</returns>
        protected bool isOwner(CollaboratorViewModel collaborator)
        {
            string userID = User.Identity.GetUserId();
            ProjectAccess access = new ProjectAccess(collaborator.ProjectID);

            if (!access.IsOwner(userID))
            {
                return false;
            }

            return true;
        }

    }
}

CodeKingdom/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CodeKingdom.Models;
using CodeKingdom.Models.Entities;
using CodeKingdom.Repositories;
using CodeKingdom.Models.ViewModels;

namespace CodeKingdom.Controllers
{
    [Authorize]
    public class FileController : Controller
    {
        private FileRepository repository = new FileRepository();
        private FolderRepository folderRepository = new FolderRepository();
        private ProjectRepository projectRepository = new ProjectRepository();

        /// <summary>
        /// Prepares viewmodel and returns view for creating a new file
        /// </summary>
        /// <param name="id">Project ID</param>
        /// <returns></returns>
        public ActionResult Create(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Project project = projectRepository.GetById(id.Value);

            if (project == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            FileViewModel model = new FileViewModel
            {
                ProjectID = project.ID,
                Folders = GetFolders(project.Root.ID)
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ProjectID,FolderID,Name,Type")] FileViewModel file)
        {
            if (ModelState.IsValid)
            {
                File newfile = repository.Create(file);
                return RedirectToAction("Details", "Project", new { id = file.ProjectID, fileID = newfile.ID});
            }

            return View(file);
        }

        /// <summary>
        /// Finds file by id to edit it. Returns updated view model.
        /// </summary>
        /// <param name="id">File ID</param>
        /// <returns></returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            File file = repository.GetById(id.Value);

            if (file == null)
            {
                return HttpNotFound();
            }

            Project project = projectRepository.GetById(id.Value);

            if (project == null)
            {
                return HttpNotFound();
            }

            FileViewModel model = new FileViewModel
            {
                ID = file.ID,
                Name = file.Name,
                ProjectID = project.ID,
                Type = file.Type,
                Folders = GetFolders(project.Root.ID)
            };

            return View(model);
        }

        // POST: File/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Type")] FileViewModel file)
        {
            if (ModelState.IsValid)
            {
                repository.Rename(file);
                return RedirectToAction("Index");
            }
            
            return View(file);
        }
        /// <summary>
        /// Finds file by ID and removes it from db
        /// </summary>
        /// <param name="id">File ID</param>
        /// <returns></returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            File file = repository.GetById(id.Value);

            if (file == null)
            {
                return HttpNotFound();
            }

            FileViewModel model = new FileViewModel
            {
                ID = file.ID,
                Name = file.Name,
                Type = file.Type,
                Content = file.Content,
            };

            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            repository.DeleteById(id);
            return RedirectToAction("Index");
        }


        /// <summary>
        /// Removes file from db by file id. Updates the file list and returns it in Json string.
        /// </summary>
        /// <param name="id">File ID</param>
        /// <returns>Json string</returns>
        [HttpPost]
        public JsonResult DeleteFile(int id)
        {
            File file = repository.GetById(id);
            Folder root = folderRepository.GetRoot(file.FolderID);
            Project project = projectRepository.GetByRootId(root.ID);
            repository.DeleteById(id);
            List<File> files = repository.GetByFolderId(root.ID);
            List<int> fileIDs = new List<int>();
            List<string> fileNames = new List<string>();
            foreach (File f in files)
            {
                fileIDs.Add(f.ID);
                fileNames.Add(f.Name);
            }

            return Json(new { ProjectID = project.ID, FileIDs = fileIDs, FileNames = fileNames }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult RenameFile(FileViewModel file)
        {
            File newFile = repository.Rename(file);
            return Json(new { Name = newFile.Name, ID = newFile.ID }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(EditorViewModel model)
        {
            FileViewModel fileModel = new FileViewModel
            {
                ID = model.FileID,
                Content = model.Content
            };
            repository.UpdateContent(fileModel);
            return RedirectToAction("Index", "Project", null);
        }

        private List<SelectListItem> GetFolders(int rootID)
        {
            List<Folder> folders = new List<Folder>();
            folders.AddRange(folderRepository.GetCascadingChildrenById(rootID));
            List<SelectListItem> folderList = new List<SelectListItem>();

            foreach (var folder in folders)
            {
                folderList.Add(new SelectListItem { Value = folder.ID.ToString(), Text = folder.Name });
            }

            return folderList;
        }
    }
}

CodeKingdom/Controllers/FolderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CodeKingdom.Models.Entities;
using CodeKingdom.Models.ViewModels;
using CodeKingdom.Repositories;

namespace CodeKingdom.Controllers
{
    [Authorize]
    public class FolderController : Controller
    {
        ProjectRepository projectRepository = new ProjectRepository();
        FolderRepository folderRepository = new FolderRepository();
       
        /// <summary>
        /// Prepares viewmodel and returns view for creating new folder
        /// </summary>
        /// <param name="id">Project ID</param>
        public ActionResult Create(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Project project = projectRepository.GetById(id.Value);

            if(project == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            List<Folder> folders = folderRepository.GetCascadingChildrenById(project.Root.ID);
            List<SelectListItem> folderList = new List<SelectListItem>();
            
            foreach (var folder in folders)
            {
                folderList.Add(new SelectListItem
                {
                    Value = folder.ID.ToString(), Text = folder.Name
                });
            }

            FolderViewModel viewModel = new FolderViewModel
            {
                ProjectID = project.ID,
                Folders = folderList
            };

            return View(viewModel);
        }

        /// <summary>
        /// Creates new folder
        /// </summary>
        /// <param name="model">F</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProjectID,FolderID,Name")] FolderViewModel model)
        {
            if (ModelState.IsValid)
            {
                Folder folder = new Folder { Name = model.Name, FolderID = model.FolderID };
                folder = folderRepository.Create(folder);
                return RedirectToAction("Details", "Project", new { id = model.ProjectID });
            }

            return View(model);
        }
    }
}

CodeKingdom/Views/Project/Create.cshtml
@model CodeKingdom.Models.ViewModels.ProjectViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CodeKingdom/Views/Project/Delete.cshtml
@model CodeKingdom.Models.ViewModels.ProjectViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CodeKingdom/Views/Project/Details.cshtml
@model CodeKingdom.Models.ViewModels.EditorViewModel

@{
    ViewBag.Title = Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/Content/jPushMenu.css")
@Styles.Render("~/Content/ChatBox.css")


@helper createFolders(CodeKingdom.Models.Entities.Folder folder, int position)
{
    <li>
        <a data-toggle="collapse" class="@(folder.ID == Model.Root.ID ? Html.Raw("root"): Html.Raw("folder"))" href="#" data-target="#folder-@folder.ID" data-folderid="@folder.ID">
            @if (folder.ID != Model.Root.ID)
            {
                <i class="fa @(position == 1 ? Html.Raw("fa-minus") : Html.Raw("fa-plus"))"></i>
            }
            <span>@Html.Raw(folder.Name)</span>
        </a>
        <ul id="folder-@folder.ID" class="@(position == 1 ? @Html.Raw("") : @Html.Raw("collapse"))">
            @foreach (var file in folder.Files)
            {
                <li><a href="/Project/Details/@Model.ProjectID/@file.ID" data-id="@file.ID" class="tree-item @(Model.FileID == file.ID ? @Html.Raw("active"):@Html.Raw("")) ">@file.Name</a></li>
            }
            @if (folder.Folders.Count > 0)
            {
                foreach (var singleFolder in folder.Folders)
                {
                    @createFolders(singleFolder, position + 1)
                }
            }
        </ul>
    </li>
}

<div>
    <!-- Project Folder/File overview on the left -->
    <nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left">
        <div id="new-folder-file">
            @Html.ActionLink("New Folder", "Create", "Folder", new { id = Model.ProjectID }, null)
            @Html.ActionLink("New File", "Create", "File", new { id = Model.ProjectID }, null)
            <span class="project-name">@Html.DisplayFor(model => model.Name) </span>
        </div>
        <ul class="menu-list" id="editormenu">

            @createFolders(Model.Root, 1)

        </ul>
    </nav>

    <!-- Right Click Context Menu -->
    <div id="cntnr">
        <ul class="right-click-items">
            <li class="menu-item"><a href="#" id="open-in-tab" class="new-tab" target="_blank">Open in new tab</a></li>
            <li class="menu-item"><a id="context-menu-rename">Rename</a></li>
            <li class="menu-item"><a id="context-menu-delete">Delete</a></li>
        </ul>
    </div>

    <div id="folderRightClickMenu">
        <ul class="right-click-items">
            <li class="menu-item"><a id="folder-menu-rename">Rename</a></li>
            <li class="menu-item"><a id="folder-menu-delete">Delete</a></li>
        </ul>
    </div>

    <!--Editor-->
    <div id="editor">@Html.Raw(Model.Content)</div>


    <!-- Chat Window -->
    <div class="chat-container">
        <div class="chat-bar">
            <div></div>
            <input type="button" class="close-chat" value=" " />
        </div>
        <div class="chat-content">
            <input type="hidden" id="displayname" />
            <ul id="discussion">
                @foreach (var chat in Model.Chats)
                {
                    <li class="show-time">
                        <i>@chat.DateTime.ToString("dd MMM HH:mm")</i>
                    </li>
                    <li class="show-name-msg">
                        @{ var username = chat.Username.Split('@');}
                        <strong>  @username[0] </strong>@chat.Message
                    </li>
                }
            </ul>
        </div>
        <div class="chat-input">
            <textarea name="textbox" id="message" placeholder="Your message here..."></textarea>
        </div>
    </div>
    <input type="hidden" id="sendmessage" value="Send" />
    <img src="/Content/Images/chat-bubble.png" id="chat-bubble" />
    <div class="active-users">
    </div>
</div>

@section scripts {
    @Scripts.Render("~/Scripts/jquery.signalR-2.2.2.min.js")
    @Scripts.Render("~/signalr/hubs")
    @Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/ace.js")
    @Scripts.Render("~/Scripts/jPushMenu.js")
    @Scripts.Render("~/Scripts/editor.js")

    <script>
        var fileID = @Model.FileID;
        var projectID = @Model.ProjectID;
        var colorscheme = '@(ViewBag.newColorscheme)';
        var keyBinding = '@(ViewBag.newKeyBinding)';
        var type = '@Model.Type';
        $(document).ready(function() {
            var $navbar = $(".navbar-fixed-top");
            $(window).unbind('scroll');
            $navbar.addClass("top-nav-collapse");
        })
    </script>

}    

CodeKingdom/Views/Project/Edit.cshtml
@model CodeKingdom.Models.ViewModels.ProjectViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">          
            <div class="col-md-2"></div>
            <div class="col-md-10">
                <table class="table">
                    <tr>
                        <th>
                            @if (Model.Role == "Owner")
                            {
                                @Html.DisplayNameFor(model => model.Collaborators) @Html.ActionLink("Add another collaborator", "Create", "Collaborator", new { id = Model.ID }, new { @class="ml15"})
                            }
                        </th>
                        <th>Role</th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model.Collaborators)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.RoleName)
                            </td>
                            <td>
                                @if (Model.Role == "Owner")
                                {
                                    @Html.ActionLink("Edit", "Edit", "Collaborator", new { id = item.ID }, null)
                                    <text> | </text>
                                    @Html.ActionLink("Delete", "Delete", "Collaborator", new { id = item.ID }, null)
                                }
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CodeKingdom/Views/Project/Index.cshtml
@model IEnumerable<CodeKingdom.Models.ViewModels.ProjectViewModel>

@{
    ViewBag.Title = "Projects";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Projects</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { }, new { @class="btn btn-default"} )
</p>

<table class="table">
<thead>
    <tr>
        <th>Name</th>
        <th>Role</th>
        <th>Settings</th>
    </tr>
</thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Name, "Details", new { id = item.ID })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Role)
                </td>
                <td>
                    @if (item.Role == "Owner")
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) <text> | </text>
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID }) <text> | </text>
                        @Html.ActionLink("Clear Chat", "ClearChat", new { id = item.ID})
                    }
                </td>
            </tr>
        }
    </tbody>
</table>